services:
  osrm:
    container_name: osrm-server
    image: osrm/osrm-backend:latest@sha256:af5d4a83fb90086a43b1ae2ca22872e6768766ad5fcbb07a29ff90ec644ee409
    ports:
      - "5001:5000"
    volumes:
      - ./osrm-data:/data
    command: "osrm-routed --algorithm mld /data/south-korea-latest.osrm"
    restart: always
    healthcheck:      # 헬스체크 설정
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - silverithm_network

networks:
  silverithm_network:
